# https://travis-ci.org/dr-prodigy/python-holidays
dist: bionic
language: python
cache: pip

before_install:
  - pip install --upgrade pip

install:
  - pip install flake8
  - pip install coveralls
  - python -m pip install -r requirements_dev.txt
  - python setup.py install


matrix:
  include:
    - python: '3.9'
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'
    - python: 'pypy3'

before_script:
    - flake8

script:
    - pytest

after_success:
    - coveralls
