name: "Tests"
on: [push, pull_request]

jobs:
  pre-commit:
    name: Run Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    name: "Test: py${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs: [pre-commit]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, pypy3]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U -r requirements_dev.txt
      # hijri-converter is not available for < python 3.6
      - name: Install hijri-converter
        if: contains( [2.7, 3.5], ${{ matrix.python-version }} ) != true
        run: |
          python -m pip install -U pip
          python -m pip install -U -r requirements_dev.txt
      - name: Run tests
        run: |
          py.test --cov=./ --cov-report term --cov-report xml --cov-config .coveragerc tests
      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: ${{ matrix.os }}-py${{ matrix.python-version }}

  deploy:
    name: Upload new version to PyPi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U -r requirements_dev.txt
          pip install -U .
      - name: Build dist
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
